version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/alemeno
    ports:
      - 8000:8000
    image: app:alemeno
    container_name: alemeno_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=alemeno_assignment
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=tester
    container_name: postgres_db
